import { useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import TagSelector from "../components/TagSelector";
import ResourceContainer from "../components/ResourceContainer";

const Home: any = () => {
  const [filter, setFilter] = useState<string[]>([]);

  function toggleFilter(tag: string): void {
    if (filter.includes(tag)) {
      setFilter(filter.filter((item) => item !== tag));
    } else {
      setFilter([...filter, tag]);
    }
  }

  return (
    <div>
      <Head>
        <title>Resources</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TagSelector filter={filter} toggleFilter={toggleFilter} />
      <ResourceContainer filter={filter} toggleFilter={toggleFilter} />
    </div>
  );
};

export default Home;
